{
 "title": "CyberPower UPS Dashboard",
 "description": "This exporter collects SNMP data from CyberPower PowerPanel Business for Linx. and exposes it as Prometheus metrics. It's designed to work with CyberPower PowerPanel Business on Linux with SNMPv1 enabled.\r\n",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "SNMP_Target",
    "label": "SNMP_Target",
    "query": {
     "query": "label_values(ups_battery_status,snmp_target)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Battery Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "upsBaseBatteryStatus" }
   ]
  },
  {
   "title": "Output Watts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "upsAdvanceOutputPower{}" }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "upsAdvanceBatteryVoltage{}" }
   ]
  },
  {
   "title": "Output Frequency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "upsAdvanceOutputFrequency{}" }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "expr": "upsAdvanceOutputCurrent * upsAdvanceOutputVoltage",
     "legendFormat": "VA"
    }
   ]
  },
  {
   "title": "Output Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "upsAdvanceOutputLoad{}", "legendFormat": "load" }
   ]
  },
  {
   "title": "Input and Output Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "upsAdvanceInputLineVoltage{}", "legendFormat": "Input Voltage" },
    { "expr": "upsAdvanceOutputVoltage{}", "legendFormat": "Output Voltage" }
   ]
  },
  {
   "title": "Output Current",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ampere" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "upsAdvanceOutputCurrent{}" }
   ]
  },
  {
   "title": "Battery Charge Remaining",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "upsAdvanceBatteryCapacity{}" }
   ]
  },
  {
   "title": "Estimated Minutes Remaining",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upsAdvanceBatteryRunTimeRemaining{}"
    }
   ]
  }
 ]
}