{
 "title": "Stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Pressure",
   "type": "bargauge",
   "description": "Resource pressure via PSI",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_pressure_cpu_waiting_seconds_total{}[$__rate_interval])",
     "legendFormat": "CPU"
    },
    {
     "expr": "rate(node_pressure_memory_waiting_seconds_total{}[$__rate_interval])",
     "legendFormat": "Mem"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "Overall CPU busy percentage (averaged across all cores)",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Temp",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"pci0000:00_0000:00:18_3\",sensor=\"temp1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "description": "Real RAM usage excluding cache and reclaimable memory",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min((1 - (node_memory_MemAvailable_bytes{} / node_memory_MemTotal_bytes{})) * 100, 0)"
    }
   ]
  },
  {
   "title": "GPU 0",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{gpu=\"0\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU 1",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{gpu=\"1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU 0",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{gpu=\"0\"})",
     "legendFormat": "{{Hostname}} - GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU 1",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{gpu=\"1\"})",
     "legendFormat": "{{Hostname}} - GPU {{gpu}}"
    }
   ]
  }
 ]
}